/**
 * 
 */
package io.driocc.devicedetector.device;

import java.util.HashMap;
import java.util.Map;

import io.driocc.devicedetector.DetectResult;
import io.driocc.devicedetector.ParserAbstract;

/**
 * @author kyon
 *
 */
public class DeviceParserAbstract extends ParserAbstract {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    protected String deviceType = null;
    protected String model = null;
    protected String brand = null;
    static final int DEVICE_TYPE_DESKTOP              = 0;
    static final int DEVICE_TYPE_SMARTPHONE           = 1;
    static final int DEVICE_TYPE_TABLET               = 2;
    static final int DEVICE_TYPE_FEATURE_PHONE        = 3;
    static final int DEVICE_TYPE_CONSOLE              = 4;
    static final int DEVICE_TYPE_TV                   = 5; // including set top boxes, blu-ray players,...
    static final int DEVICE_TYPE_CAR_BROWSER          = 6;
    static final int DEVICE_TYPE_SMART_DISPLAY        = 7;
    static final int DEVICE_TYPE_CAMERA               = 8;
    static final int DEVICE_TYPE_PORTABLE_MEDIA_PAYER = 9;
    static final int DEVICE_TYPE_PHABLET              = 10;
	private static Map<String, Integer> deviceTypes = new HashMap<String, Integer>();
	private static Map<String, String> deviceBrands = new HashMap<String, String>();
	
	static{
		deviceTypes.put("desktop", DEVICE_TYPE_DESKTOP);
		deviceTypes.put("smartphone", DEVICE_TYPE_SMARTPHONE);
		deviceTypes.put("tablet", DEVICE_TYPE_TABLET);
		deviceTypes.put("feature phone", DEVICE_TYPE_FEATURE_PHONE);
		deviceTypes.put("console", DEVICE_TYPE_CONSOLE);
		deviceTypes.put("tv", DEVICE_TYPE_TV);
		deviceTypes.put("car browser", DEVICE_TYPE_CAR_BROWSER);
		deviceTypes.put("smart display", DEVICE_TYPE_SMART_DISPLAY);
		deviceTypes.put("camera", DEVICE_TYPE_CAMERA);
		deviceTypes.put("portable media player", DEVICE_TYPE_PORTABLE_MEDIA_PAYER);
		deviceTypes.put("phablet", DEVICE_TYPE_PHABLET);
		deviceBrands.put("3Q", "3Q");
        deviceBrands.put("AC", "Acer");
        deviceBrands.put("AZ", "Ainol");
        deviceBrands.put("AI", "Airness");
        deviceBrands.put("AL", "Alcatel");
        deviceBrands.put("A2", "Allview");
        deviceBrands.put("A1", "Altech UEC");
        deviceBrands.put("AN", "Arnova");
        deviceBrands.put("KN", "Amazon");
        deviceBrands.put("AO", "Amoi");
        deviceBrands.put("AP", "Apple");
        deviceBrands.put("AR", "Archos");
        deviceBrands.put("AS", "ARRIS");
        deviceBrands.put("AT", "Airties");
        deviceBrands.put("AU", "Asus");
        deviceBrands.put("AV", "Avvio");
        deviceBrands.put("AX", "Audiovox");
        deviceBrands.put("AY", "Axxion");
        deviceBrands.put("BB", "BBK");
        deviceBrands.put("BE", "Becker");
        deviceBrands.put("BI", "Bird");
        deviceBrands.put("BL", "Beetel");
        deviceBrands.put("BM", "Bmobile");
        deviceBrands.put("BN", "Barnes & Noble");
        deviceBrands.put("BO", "BangOlufsen");
        deviceBrands.put("BQ", "BenQ");
        deviceBrands.put("BS", "BenQ-Siemens");
        deviceBrands.put("BU", "Blu");
        deviceBrands.put("BW", "Boway");
        deviceBrands.put("BX", "bq");
        deviceBrands.put("BV", "Bravis");
        deviceBrands.put("BR", "Brondi");
        deviceBrands.put("B1", "Bush");
        deviceBrands.put("CB", "CUBOT");
        deviceBrands.put("CF", "Carrefour");
        deviceBrands.put("CP", "Captiva");
        deviceBrands.put("CS", "Casio");
        deviceBrands.put("CA", "Cat");
        deviceBrands.put("CE", "Celkon");
        deviceBrands.put("CC", "ConCorde");
        deviceBrands.put("C2", "Changhong");
        deviceBrands.put("CH", "Cherry Mobile");
        deviceBrands.put("CK", "Cricket");
        deviceBrands.put("C1", "Crosscall");
        deviceBrands.put("CL", "Compal");
        deviceBrands.put("CN", "CnM");
        deviceBrands.put("CM", "Crius Mea");
        deviceBrands.put("CR", "CreNova");
        deviceBrands.put("CT", "Capitel");
        deviceBrands.put("CQ", "Compaq");
        deviceBrands.put("CO", "Coolpad");
        deviceBrands.put("CW", "Cowon");
        deviceBrands.put("CU", "Cube");
        deviceBrands.put("CY", "Coby Kyros");
        deviceBrands.put("DA", "Danew");
        deviceBrands.put("DT", "Datang");
        deviceBrands.put("DE", "Denver");
        deviceBrands.put("DS", "Desay");
        deviceBrands.put("DB", "Dbtel");
        deviceBrands.put("DC", "DoCoMo");
        deviceBrands.put("DI", "Dicam");
        deviceBrands.put("DL", "Dell");
        deviceBrands.put("DN", "DNS");
        deviceBrands.put("DM", "DMM");
        deviceBrands.put("DO", "Doogee");
        deviceBrands.put("DV", "Doov");
        deviceBrands.put("DP", "Dopod");
        deviceBrands.put("DU", "Dune HD");
        deviceBrands.put("EB", "E-Boda");
        deviceBrands.put("EA", "EBEST");
        deviceBrands.put("EC", "Ericsson");
        deviceBrands.put("ES", "ECS");
        deviceBrands.put("EI", "Ezio");
        deviceBrands.put("EL", "Elephone");
        deviceBrands.put("EP", "Easypix");
        deviceBrands.put("E1", "Energy Sistem");
        deviceBrands.put("ER", "Ericy");
        deviceBrands.put("EN", "Eton");
        deviceBrands.put("ET", "eTouch");
        deviceBrands.put("EV", "Evertek");
        deviceBrands.put("EX", "Explay");
        deviceBrands.put("EZ", "Ezze");
        deviceBrands.put("FA", "Fairphone");
        deviceBrands.put("FL", "Fly");
        deviceBrands.put("FO", "Foxconn");
        deviceBrands.put("FU", "Fujitsu");
        deviceBrands.put("GM", "Garmin-Asus");
        deviceBrands.put("GA", "Gateway");
        deviceBrands.put("GD", "Gemini");
        deviceBrands.put("GI", "Gionee");
        deviceBrands.put("GG", "Gigabyte");
        deviceBrands.put("GS", "Gigaset");
        deviceBrands.put("GC", "GOCLEVER");
        deviceBrands.put("GL", "Goly");
        deviceBrands.put("GO", "Google");
        deviceBrands.put("GR", "Gradiente");
        deviceBrands.put("GU", "Grundig");
        deviceBrands.put("HA", "Haier");
        deviceBrands.put("HS", "Hasee");
        deviceBrands.put("HI", "Hisense");
        deviceBrands.put("HL", "Hi-Level");
        deviceBrands.put("HM", "Homtom");
        deviceBrands.put("HO", "Hosin");
        deviceBrands.put("HP", "HP");
        deviceBrands.put("HT", "HTC");
        deviceBrands.put("HU", "Huawei");
        deviceBrands.put("HX", "Humax");
        deviceBrands.put("HY", "Hyrican");
        deviceBrands.put("HN", "Hyundai");
        deviceBrands.put("IA", "Ikea");
        deviceBrands.put("IB", "iBall");
        deviceBrands.put("IJ", "i-Joy");
        deviceBrands.put("IY", "iBerry");
        deviceBrands.put("IK", "iKoMo");
        deviceBrands.put("IM", "i-mate");
        deviceBrands.put("I1", "iOcean");
        deviceBrands.put("IW", "iNew");
        deviceBrands.put("IF", "Infinix");
        deviceBrands.put("IN", "Innostream");
        deviceBrands.put("II", "Inkti");
        deviceBrands.put("IX", "Intex");
        deviceBrands.put("IO", "i-mobile");
        deviceBrands.put("IQ", "INQ");
        deviceBrands.put("IT", "Intek");
        deviceBrands.put("IV", "Inverto");
        deviceBrands.put("IZ", "iTel");
        deviceBrands.put("JI", "Jiayu");
        deviceBrands.put("JO", "Jolla");
        deviceBrands.put("KA", "Karbonn");
        deviceBrands.put("KD", "KDDI");
        deviceBrands.put("K1", "Kiano");
        deviceBrands.put("KI", "Kingsun");
        deviceBrands.put("KO", "Konka");
        deviceBrands.put("KM", "Komu");
        deviceBrands.put("KB", "Koobee");
        deviceBrands.put("KT", "K-Touch");
        deviceBrands.put("KH", "KT-Tech");
        deviceBrands.put("KP", "KOPO");
        deviceBrands.put("KR", "Koridy");
        deviceBrands.put("KU", "Kumai");
        deviceBrands.put("KY", "Kyocera");
        deviceBrands.put("KZ", "Kazam");
        deviceBrands.put("LV", "Lava");
        deviceBrands.put("LA", "Lanix");
        deviceBrands.put("LC", "LCT");
        deviceBrands.put("L1", "LeEco");
        deviceBrands.put("LE", "Lenovo");
        deviceBrands.put("LN", "Lenco");
        deviceBrands.put("LP", "Le Pan");
        deviceBrands.put("LG", "LG");
        deviceBrands.put("LI", "Lingwin");
        deviceBrands.put("LO", "Loewe");
        deviceBrands.put("LM", "Logicom");
        deviceBrands.put("LX", "Lexibook");
        deviceBrands.put("MJ", "Majestic");
        deviceBrands.put("MA", "Manta Multimedia");
        deviceBrands.put("MB", "Mobistel");
        deviceBrands.put("M3", "Mecer");
        deviceBrands.put("MD", "Medion");
        deviceBrands.put("M2", "MEEG");
        deviceBrands.put("M1", "Meizu");
        deviceBrands.put("ME", "Metz");
        deviceBrands.put("MX", "MEU");
        deviceBrands.put("MI", "MicroMax");
        deviceBrands.put("M5", "MIXC");
        deviceBrands.put("MC", "Mediacom");
        deviceBrands.put("MK", "MediaTek");
        deviceBrands.put("MO", "Mio");
        deviceBrands.put("MM", "Mpman");
        deviceBrands.put("M4", "Modecom");
        deviceBrands.put("MF", "Mofut");
        deviceBrands.put("MR", "Motorola");
        deviceBrands.put("MS", "Microsoft");
        deviceBrands.put("MZ", "MSI");
        deviceBrands.put("MU", "Memup");
        deviceBrands.put("MT", "Mitsubishi");
        deviceBrands.put("ML", "MLLED");
        deviceBrands.put("MQ", "M.T.T.");
        deviceBrands.put("MY", "MyPhone");
        deviceBrands.put("NE", "NEC");
        deviceBrands.put("NA", "Netgear");
        deviceBrands.put("NG", "NGM");
        deviceBrands.put("NO", "Nous");
        deviceBrands.put("NI", "Nintendo");
        deviceBrands.put("N1", "Noain");
        deviceBrands.put("NK", "Nokia");
        deviceBrands.put("NM", "Nomi");
        deviceBrands.put("NN", "Nikon");
        deviceBrands.put("NW", "Newgen");
        deviceBrands.put("NX", "Nexian");
        deviceBrands.put("NT", "NextBook");
        deviceBrands.put("OD", "Onda");
        deviceBrands.put("ON", "OnePlus");
        deviceBrands.put("OP", "OPPO");
        deviceBrands.put("OR", "Orange");
        deviceBrands.put("OT", "O2");
        deviceBrands.put("OK", "Ouki");
        deviceBrands.put("OU", "OUYA");
        deviceBrands.put("OO", "Opsson");
        deviceBrands.put("PA", "Panasonic");
        deviceBrands.put("PE", "PEAQ");
        deviceBrands.put("PG", "Pentagram");
        deviceBrands.put("PH", "Philips");
        deviceBrands.put("PI", "Pioneer");
        deviceBrands.put("PL", "Polaroid");
        deviceBrands.put("PM", "Palm");
        deviceBrands.put("PO", "phoneOne");
        deviceBrands.put("PT", "Pantech");
        deviceBrands.put("PY", "Ployer");
        deviceBrands.put("PV", "Point of View");
        deviceBrands.put("PP", "PolyPad");
        deviceBrands.put("P2", "Pomp");
        deviceBrands.put("PS", "Positivo");
        deviceBrands.put("PR", "Prestigio");
        deviceBrands.put("P1", "ProScan");
        deviceBrands.put("PU", "PULID");
        deviceBrands.put("QI", "Qilive");
        deviceBrands.put("QT", "Qtek");
        deviceBrands.put("QM", "QMobile");
        deviceBrands.put("QU", "Quechua");
        deviceBrands.put("OV", "Overmax");
        deviceBrands.put("OY", "Oysters");
        deviceBrands.put("RA", "Ramos");
        deviceBrands.put("RC", "RCA Tablets");
        deviceBrands.put("RB", "Readboy");
        deviceBrands.put("RI", "Rikomagic");
        deviceBrands.put("RM", "RIM");
        deviceBrands.put("RK", "Roku");
        deviceBrands.put("RO", "Rover");
        deviceBrands.put("SA", "Samsung");
        deviceBrands.put("SD", "Sega");
        deviceBrands.put("SE", "Sony Ericsson");
        deviceBrands.put("S1", "Sencor");
        deviceBrands.put("SF", "Softbank");
        deviceBrands.put("SX", "SFR");
        deviceBrands.put("SG", "Sagem");
        deviceBrands.put("SH", "Sharp");
        deviceBrands.put("SI", "Siemens");
        deviceBrands.put("SN", "Sendo");
        deviceBrands.put("S6", "Senseit");
        deviceBrands.put("SK", "Skyworth");
        deviceBrands.put("SC", "Smartfren");
        deviceBrands.put("SO", "Sony");
        deviceBrands.put("SP", "Spice");
        deviceBrands.put("SU", "SuperSonic");
        deviceBrands.put("S5", "Supra");
        deviceBrands.put("SV", "Selevision");
        deviceBrands.put("SY", "Sanyo");
        deviceBrands.put("SM", "Symphony");
        deviceBrands.put("SR", "Smart");
        deviceBrands.put("S7", "Smartisan");
        deviceBrands.put("S4", "Star");
        deviceBrands.put("ST", "Storex");
        deviceBrands.put("S2", "Stonex");
        deviceBrands.put("S3", "SunVan");
        deviceBrands.put("SZ", "Sumvision");
        deviceBrands.put("TA", "Tesla");
        deviceBrands.put("T5", "TB Touch");
        deviceBrands.put("TC", "TCL");
        deviceBrands.put("TE", "Telit");
        deviceBrands.put("T4", "ThL");
        deviceBrands.put("TH", "TiPhone");
        deviceBrands.put("TB", "Tecno Mobile");
        deviceBrands.put("TD", "Tesco");
        deviceBrands.put("TI", "TIANYU");
        deviceBrands.put("TL", "Telefunken");
        deviceBrands.put("T2", "Telenor");
        deviceBrands.put("TM", "T-Mobile");
        deviceBrands.put("TN", "Thomson");
        deviceBrands.put("T1", "Tolino");
        deviceBrands.put("TO", "Toplux");
        deviceBrands.put("TS", "Toshiba");
        deviceBrands.put("TT", "TechnoTrend");
        deviceBrands.put("T3", "Trevi");
        deviceBrands.put("TU", "Tunisie Telecom");
        deviceBrands.put("TR", "Turbo-X");
        deviceBrands.put("TV", "TVC");
        deviceBrands.put("TX", "TechniSat");
        deviceBrands.put("TZ", "teXet");
        deviceBrands.put("UN", "Unowhy");
        deviceBrands.put("US", "Uniscope");
        deviceBrands.put("UT", "UTStarcom");
        deviceBrands.put("VA", "Vastking");
        deviceBrands.put("VD", "Videocon");
        deviceBrands.put("VE", "Vertu");
        deviceBrands.put("VI", "Vitelcom");
        deviceBrands.put("VK", "VK Mobile");
        deviceBrands.put("VS", "ViewSonic");
        deviceBrands.put("VT", "Vestel");
        deviceBrands.put("VV", "Vivo");
        deviceBrands.put("V1", "Voto");
        deviceBrands.put("VO", "Voxtel");
        deviceBrands.put("VF", "Vodafone");
        deviceBrands.put("VZ", "Vizio");
        deviceBrands.put("VW", "Videoweb");
        deviceBrands.put("WA", "Walton");
        deviceBrands.put("WE", "WellcoM");
        deviceBrands.put("WY", "Wexler");
        deviceBrands.put("WI", "Wiko");
        deviceBrands.put("WL", "Wolder");
        deviceBrands.put("WO", "Wonu");
        deviceBrands.put("WX", "Woxter");
        deviceBrands.put("XI", "Xiaomi");
        deviceBrands.put("XO", "Xolo");
        deviceBrands.put("YA", "Yarvik");
        deviceBrands.put("YU", "Yuandao");
        deviceBrands.put("YS", "Yusun");
        deviceBrands.put("YT", "Ytone");
        deviceBrands.put("ZE", "Zeemi");
        deviceBrands.put("ZO", "Zonda");
        deviceBrands.put("ZP", "Zopo");
        deviceBrands.put("ZT", "ZTE");
        deviceBrands.put("WB", "Web TV");
        deviceBrands.put("XX", "Unknown");
	}
	/**
	 * @param userAgent
	 * @return
	 */
	public DetectResult parse(String userAgent) {
		// TODO Auto-generated method stub
		return null;
	}
}
